
//Primitive data types in JavaScript include:
//Numbers - Integers, floats
//Strings - Any data under single quote, double quote or backtick quote
//Booleans - true or false value
//Null - empty value or no value
//Undefined - a declared variable without a value
//Symbol - A unique value that can be generated by Symbol constructor


//Non-primitive data types in JavaScript includes:

//Objects
//Arrays

/*
Escape Sequences in Strings

\n: new line
\t: Tab, means 8 spaces
\\: Back slash
\': Single quote (')
\": Double quote (")

*/

//Math Object
/* In JavaScript the Math Object provides a lots of methods to work with numbers.

console.log(Math.round(PI))                // 3 to round values to the nearest number

console.log(Math.round(9.81))              // 10

console.log(Math.floor(PI))                // 3 rounding down

console.log(Math.ceil(PI))                 // 4 rounding up

console.log(Math.min(-5, 3, 20, 4, 5, 10)) // -5, returns the minimum value

console.log(Math.max(-5, 3, 20, 4, 5, 10)) // 20, returns the maximum value

onst randNum = Math.random() // creates random number between 0 to 0.999999
console.log(randNum)

*Let us  create random number between 0 to 10*

const num = Math.floor(Math.random () * 11) // creates random number between 0 and 10
console.log(num)

*Absolute value*
console.log(Math.abs(-10))      // 10

*Square root*
console.log(Math.sqrt(100))     // 10

console.log(Math.sqrt(2))       // 1.4142135623730951

*Power*
console.log(Math.pow(3, 2))     // 9

console.log(Math.E)             // 2.718

*Logarithm*
Returns the natural logarithm with base E of x, Math.log(x)

console.log(Math.log(2))        // 0.6931471805599453
console.log(Math.log(10))       // 2.302585092994046

*Returns the natural logarithm of 2 and 10 respectively*
console.log(Math.LN2)           // 0.6931471805599453
console.log(Math.LN10)          // 2.302585092994046

*Trigonometry*
Math.sin(0)
Math.sin(60)

Math.cos(0)
Math.cos(60)
*/ 

/*

*Template Literals (Template Strings)*
Syntax
`String literal text`
`String literal text ${expression}` 

Example: 1

console.log(`The sum of 2 and 3 is 5`)  // statically writing the data
let a = 2
let b = 3
console.log(`The sum of ${a} and ${b} is ${a + b}`) // injecting the data dynamically

*/

//String methods

/*
1. Length

Example
let js = 'JavaScript'
console.log(js.length) // 10

Access different characters in 'JavaScript' string.

let string = 'JavaScript'
let firstLetter = string[0]
let secondLetter = string[1]

console.log(firstLetter)           // J
console.log(secondLetter)           // a

2. toUpperCase()

Example
let string = 'JavaScript'
console.log(string.toUpperCase())     // JAVASCRIPT

3.toLowerCase(): 

Example
let string = 'JavasCript'
console.log(string.toLowerCase())     // javascript


4.
substr(): It takes two arguments, 
the starting index and number of characters to slice.

Example
let string = 'JavaScript'
console.log(string.substr(4,6))    // Script - Starting index is 4 = S then it will start to count on S so it wwll be 6

5.substring(): It takes two arguments, the starting index and the stopping index 
but it doesn't include the character at the stopping index


let string = 'JavaScript'

console.log(string.substring(0,4))     // Java
The starting index is 0 = J then it will stop on index 4 = S

6.
split(): The split method splits a string at a specified place.

let string = '30 Days Of JavaScript'

console.log(string.split())  //change to an array

let countries = 'Finland, Sweden, Norway, Denmark, and Iceland'

console.log(countries.split(','))  // split to any array at comma -> ["Finland", " Sweden", " Norway", " Denmark", " and Iceland"]
console.log(countries.split(', ')) //  ["Finland", "Sweden", "Norway", "Denmark", "and Iceland"]

In the first split with comma there are space in the second index up tp thee last index
In the second split with comma there no space in the second index up tp thee last index

7. trim(): Removes trailing space in the beginning or the end of a string.

Example:
let string = '   30 Days Of JavaScript   '

console.log(string)  // 30 Days Of JavasCript   

console.log(string.trim(' ')) //30 Days Of JavasCript

8.includes(): It takes a substring argument and it checks if substring argument exists in the string. includes() returns a boolean. 
If a substring exist in a string, it returns true, otherwise it returns false.

*It is Case Sensitive

let string = '30 Days Of JavaScript'

console.log(string.includes('Days'))     // true
console.log(string.includes('days'))     // false - it is case sensitive!
console.log(string.includes('Script'))   // true
console.log(string.includes('script'))   // false


9. replace(): takes as a parameter the old substring and a new substring.

let string = '30 Days Of JavaScript'
console.log(string.replace('JavaScript', 'Python')) // 30 Days Of Python


10. charAt(): Takes index and it returns the value at that index

let lastIndex = string.length - 1
console.log(string.charAt(lastIndex)) // t

11. charCodeAt(): Takes index and it returns char code (ASCII number) of the value at that index

let string = '30 Days Of JavaScript'
console.log(string.charCodeAt(3))        // D ASCII number is 68

12.indexOf(): Takes a substring and if the substring exists in a string it returns
the first position of the substring if does not exist it returns -1

let string = '30 Days Of JavaScript'

console.log(string.indexOf('D'))          // 3

13. lastIndexOf(): Takes a substring and if the substring exists in a string it returns the last position of the substring if it does not exist it returns -1

let string = 'I love JavaScript. If you do not love JavaScript what else can you love.'
console.log(string.lastIndexOf('love'))       // 67

14. concat(): it takes many substrings and joins them.
let string = '30'
console.log(string.concat("Days", "Of", "JavaScript")) // 30DaysOfJavaScript


15. startsWith()  it takes a substring as an argument and it checks if the string starts with that specified substring. It returns a boolean(true or false).
*Not Case Sensiive

let string = 'Love is the best to in this world'

console.log(string.startsWith('Love'))   // true
console.log(string.startsWith('world'))  // false


16. endsWith(): it takes a substring as an argument and it checks if the string ends with that specified substring. It returns a boolean(true or false).

let string = 'Love is the most powerful feeling in the world'
console.log(string.endsWith('world'))         // true
console.log(string.endsWith('love'))          // false


17. search(): it takes a substring as an argument and it returns the index of the first match. The search value can be a string or a regular expression pattern.

let string = 'I love JavaScript. If you do not love JavaScript what else can you love.'
console.log(string.search('love'))          // 2
console.log(string.search(/javascript/gi))  // 7 --> g-means to search in the whole text, i - case insensitive


18.match(): it takes a substring or regular expression pattern as an argument and it returns an array if there is match if not it returns null. Let us see how a regular expression pattern looks like. It starts with / sign and ends with / sign.

let string = 'I love JavaScript. If you do not love JavaScript what else can you love.'
console.log(string.match('love'))

Output:
[
  'love',
  index: 2,
  input: 'I love JavaScript. If you do not love JavaScript what else can you love.',
  groups: undefined
]

*Extract Numbeers from thee text

let txt = 'In 2019, I ran 30 Days of Python. Now, in 2020 I am super exited to start this challenge'
let regEx = /\d+/

-- d with escape character means d not a normal d instead acts a digit
-- + means one or more digit numbers,
-- if there is g after that it means global, search everywhere.

console.log(txt.match(regEx))  // ["2", "0", "1", "9", "3", "0", "2", "0", "2", "0"]
console.log(txt.match(/\d+/g)) // ["2019", "30", "2020"]

19. repeat(): it takes a number as argument and it returns the repeated version of the string.
string.repeat(n)

let string = 'love'
console.log(string.repeat(10)) // lovelovelovelovelovelovelovelovelovelove



Casting of DATA
Casting: Converting one data type to another data type
We can convert string to number using the following methods:

--parseInt()
--Number()
--Plus sign(+)


*String to Int

let num = '10'
let numInt = parseInt(num)
console.log(numInt) // 10


*String to Float

let num = '9.81'
let numFloat = parseFloat(num)

console.log(numFloat) // 9.81


*Float to Int
let num = 9.81
let numInt = parseInt(num)

console.log(numInt) // 9


*/







